# Generated by Django 2.2.5 on 2019-11-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_remove_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
