# Generated by Django 2.2.5 on 2019-11-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_postimage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='light_count',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='workoff_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
